// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrwquzbcqrqxwutwijxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyd3F1emJjcXJxeHd1dHdpanhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDU2NjQsImV4cCI6MjA3NDM4MTY2NH0.75O79n2qZAfdFTkwNhW4DrvYUJUHii2EYxrWcJu6av8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});